version: '3'

services:
  appscore.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  appscore.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

